version: '3.4'

services:
  messageendpoint:
    image: ${DOCKER_REGISTRY-}messageendpoint
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - Storage__serviceUri
    - MESSAGE_ENDPOINT_COMPONENT
    - MESSAGE_ENDPOINT_TOPIC
    - AZURE_TENANT_ID
    - AZURE_CLIENT_ID
    - AZURE_CLIENT_SECRET
    - APP_ID
    - APP_PORT
    - DAPR_GRPC_PORT
    - DAPR_HTTP_PORT

  messageendpoint-dapr:
    image: daprio/daprd:latest
    environment:
    - APP_ID
    - APP_PORT
    - DAPR_GRPC_PORT
    - DAPR_HTTP_PORT
    command: ["./daprd",
    "-app-id", "${APP_ID}",
    "-app-port", "${APP_PORT}",
    "-dapr-grpc-port", "${DAPR_GRPC_PORT}",
    "-dapr-http-port", "${DAPR_HTTP_PORT}",
    "-components-path", "/components"]
    volumes:
    - "../../DaprConfig:/components"
    depends_on: 
    - messageendpoint
    network_mode: service:messageendpoint