version: '3.4'

services:
  channeladapter:
    image: ${DOCKER_REGISTRY-}channeladapter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - ChannelAdapter__Interval
    - ChannelAdapter__Source
    - ChannelAdapter__DestinationComponent
    - ChannelAdapter__DestinationTopic
    - AZURE_TENANT_ID
    - AZURE_CLIENT_ID
    - AZURE_CLIENT_SECRET
    - APP_ID
    - APP_PORT
    - DAPR_GRPC_PORT
    - DAPR_HTTP_PORT

  channeladapter-dapr:
    image: daprio/daprd:latest
    environment:
    - APP_ID
    - APP_PORT
    - DAPR_GRPC_PORT
    - DAPR_HTTP_PORT
    command: ["./daprd",
    "-app-id", "${APP_ID}",
    "-app-port", "${APP_PORT}",
    "-dapr-grpc-port", "${DAPR_GRPC_PORT}",
    "-dapr-http-port", "${DAPR_HTTP_PORT}",
    "-components-path", "/components"]
    volumes:
    - "../../DaprConfig:/components"
    depends_on: 
    - channeladapter
    network_mode: service:channeladapter