version: '3.4'

services:
  channeladapter:
    image: ${DOCKER_REGISTRY-}channeladapter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - ChannelAdapter__Interval
    - ChannelAdapter__Source
    - ChannelAdapter__DestinationComponent
    - ChannelAdapter__DestinationTopic
